import type { Team, RoleSet } from './types';

export interface RoleSeed {
  name: string;
  team: Team;
  set: RoleSet;
  night_wake_order: number; // 0 = does not wake at night
  is_night_role: number;    // 1 = wakes at night, 0 = passive
  default_count: number;
  ability: string;
  moderator_script: string;
  moderator_script_tl: string; // Taglish translation
}

// ─── Night Wake Order Reference ──────────────────────────────
// 5   Sentinel (Night 1 only)
// 10  Doppelganger (Night 1 only)
// 15  Cupid (Night 1 only)
// 20  Cult Leader
// 25  Vampire / Count Dracula
// 30  Leprechaun
// 35  Thing (That Goes Bump in the Night)
// 38  Old Hag
// 40  Spellcaster
// 45  Bodyguard
// 48  Apprentice Seer
// 50  Seer
// 52  Sorceress
// 55  PI (Paranormal Investigator)
// 58  Mystic Wolf
// 60  Alpha Wolf
// 62  Lone Wolf
// 64  Dire Wolf
// 65  Fruit Brute
// 70  Werewolves (pack kill)
// 75  Witch
// 78  Insomniac
// 80  Revealer
// 85  Nostradamus
// 90  Tough Guy (passive wake — told they survived)

export const ROLE_SEED: RoleSeed[] = [
  // ═══ DELUXE SET ═══════════════════════════════════════════

  {
    name: 'Villager',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 3,
    ability: 'No special ability. Uses discussion and deduction to identify werewolves.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Werewolf',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 70,
    is_night_role: 1,
    default_count: 2,
    ability: 'Each night, wakes with the other werewolves to choose a victim to eliminate.',
    moderator_script: 'Werewolves, open your eyes and look for other werewolves. Werewolves, pick someone to eliminate. [Wait for consensus.] Werewolves, close your eyes.',
    moderator_script_tl: 'Mga Werewolf, imulat ang inyong mga mata at tingnan ang iba pang werewolf. Pumili kayo ng player na i-e-eliminate. [Hintayin ang desisyon.] Mga Werewolf, ipikit ang inyong mga mata.',
  },
  {
    name: 'Seer',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 50,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, may look at one player\'s card. The Seer only views wolves, not any other kind of role. Thumbs up if wolf, thumbs down for everyone else.',
    moderator_script: 'Seer, open your eyes. Point at a player you wish to investigate. [Give thumbs up if the player is a wolf, thumbs down if they are anything else. The Seer only detects wolves.] Seer, close your eyes.',
    moderator_script_tl: 'Seer, imulat mo ang iyong mga mata. Ituro ang isang player na gusto mong i-investigate. [Thumbs up kung wolf, thumbs down kung hindi wolf. Wolves lang ang nakikita ng Seer.] Seer, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Bodyguard',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 45,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, protects one player from elimination. Cannot protect the same player two nights in a row.',
    moderator_script: 'Bodyguard, open your eyes. Point at someone you wish to protect tonight. [You cannot choose the same player as last night.] Bodyguard, close your eyes.',
    moderator_script_tl: 'Bodyguard, imulat mo ang iyong mga mata. Ituro ang player na gusto mong protektahan ngayong gabi. [Hindi pwede yung parehong player kagabi.] Bodyguard, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Witch',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 75,
    is_night_role: 1,
    default_count: 1,
    ability: 'Has two one-time potions: a healing potion to save the werewolves\' victim, and a poison potion to eliminate another player. Once the Witch uses either power, they no longer learn who was targeted each night.',
    moderator_script: 'Witch, open your eyes. [If Witch has not used either potion yet:] This player was targeted by the werewolves tonight. [Point to victim.] Would you like to use your healing potion to save them? [Wait.] Would you like to use your poison potion on someone? [Wait for target if yes.] [If Witch has used a potion before: Do NOT reveal the target.] Witch, close your eyes.',
    moderator_script_tl: 'Witch, imulat mo ang iyong mga mata. [Kung hindi pa nagamit ang kahit anong potion:] Itong player ang target ng mga werewolf ngayong gabi. [Ituro ang biktima.] Gusto mo bang gamitin ang healing potion para i-save siya? [Hintayin.] Gusto mo bang gamitin ang poison potion sa ibang player? [Hintayin ang target kung oo.] [Kung may nagamit nang potion dati: HUWAG ipakita ang target.] Witch, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Hunter',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'When the Hunter is eliminated (day or night), they immediately choose another player to take with them.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Prince',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If the Prince is voted to be lynched, the Prince reveals their role and is not eliminated. The village falls asleep immediately after, as if the elimination was successful. Only works against lynching, not night kills.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Tanner',
    team: 'tanner',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'The Tanner wins if they are lynched during the day. They are on no one\'s team.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Mason',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 2,
    ability: 'Masons know who the other Masons are. They are confirmed villagers to each other.',
    moderator_script: 'Masons, open your eyes and look at the other Masons. Masons, close your eyes.',
    moderator_script_tl: 'Mga Mason, imulat ang inyong mga mata at tingnan ang iba pang Mason. Mga Mason, ipikit ang inyong mga mata.',
  },
  {
    name: 'Minion',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Knows who the werewolves are but is not a werewolf. If the Minion is lynched, the village does not win. Werewolves do not know who the Minion is.',
    moderator_script: 'Werewolves, extend your thumbs. Minion, open your eyes. These are the werewolves. Minion, close your eyes. Werewolves, put your thumbs down.',
    moderator_script_tl: 'Mga Werewolf, itaas ang inyong mga daliri. Minion, imulat mo ang iyong mga mata. Ito ang mga werewolf. Minion, ipikit mo ang iyong mga mata. Mga Werewolf, ibaba ang inyong mga daliri.',
  },
  {
    name: 'Drunk',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'The Drunk thinks they are a Villager but doesn\'t know their true identity. They have no special power.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Insomniac',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 78,
    is_night_role: 1,
    default_count: 1,
    ability: 'Wakes up at the end of each night to check if their role has changed (due to Alpha Wolf, Doppelganger, etc.).',
    moderator_script: 'Insomniac, open your eyes. [If their role changed, show new card. If not, give thumbs up.] Insomniac, close your eyes.',
    moderator_script_tl: 'Insomniac, imulat mo ang iyong mga mata. [Kung nagbago ang role, ipakita ang bagong card. Kung hindi, thumbs up.] Insomniac, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Cursed',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Starts as a villager. If targeted by werewolves, becomes a werewolf instead of dying. The Seer sees them as a villager until turned.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Diseased',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If eliminated by werewolves, the werewolves cannot eliminate anyone the following night.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Cupid',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 15,
    is_night_role: 1,
    default_count: 1,
    ability: 'On the first night, chooses two players to be linked as lovers. If one lover dies, the other immediately dies of heartbreak.',
    moderator_script: 'Cupid, open your eyes. Point at two players to link as lovers. [Note the two players.] Cupid, close your eyes. Lovers, open your eyes and see each other. Lovers, close your eyes.',
    moderator_script_tl: 'Cupid, imulat mo ang iyong mga mata. Ituro ang dalawang player na gusto mong i-link bilang mag-lovers. [Tandaan ang dalawa.] Cupid, ipikit mo ang iyong mga mata. Mga Lovers, imulat ang inyong mga mata at tingnan ang isa\\\'t isa. Mga Lovers, ipikit ang inyong mga mata.',
  },
  {
    name: 'Lone Wolf',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 62,
    is_night_role: 1,
    default_count: 1,
    ability: 'Wakes with the werewolves but also has a separate kill each night. The Lone Wolf only wins if they are the last werewolf alive when the werewolf team wins.',
    moderator_script: 'Lone Wolf, open your eyes. Choose a player to eliminate independently. [This is separate from the pack kill.] Lone Wolf, close your eyes.',
    moderator_script_tl: 'Lone Wolf, imulat mo ang iyong mga mata. Pumili ng player na i-e-eliminate nang mag-isa. [Hiwalay ito sa pack kill.] Lone Wolf, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Dream Wolf',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Is a werewolf but does not wake at night with the other werewolves. The Seer sees them as a werewolf.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Mystic Wolf',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 58,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, before the werewolf kill, may look at one player\'s card. Also participates in the werewolf pack kill.',
    moderator_script: 'Mystic Wolf, open your eyes. Point at a player whose card you wish to see. [Show the card.] Mystic Wolf, close your eyes.',
    moderator_script_tl: 'Mystic Wolf, imulat mo ang iyong mga mata. Ituro ang isang player na gusto mong tingnan ang card. [Ipakita ang card.] Mystic Wolf, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Alpha Wolf',
    team: 'werewolf',
    set: 'deluxe',
    night_wake_order: 60,
    is_night_role: 1,
    default_count: 1,
    ability: 'Once per game, after the werewolf kill, may convert one non-werewolf player into a werewolf.',
    moderator_script: 'Alpha Wolf, open your eyes. Do you wish to convert a player to a werewolf tonight? [If yes, point to target. This can only be used once per game.] Alpha Wolf, close your eyes.',
    moderator_script_tl: 'Alpha Wolf, imulat mo ang iyong mga mata. Gusto mo bang mag-convert ng player para maging werewolf ngayong gabi? [Kung oo, ituro ang target. Isang beses lang ito sa buong laro.] Alpha Wolf, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Village Idiot',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'The Village Idiot must always vote to lynch during the day. If they don\'t, they die. They are on the village team.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Revealer',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 80,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, may choose to flip over a player\'s card. If that player is a werewolf, they are immediately eliminated. If the Revealer points to a Lycan, the Lycan is eliminated instead of the Revealer. Do not indicate to the Revealer if their target is a wolf or lycan.',
    moderator_script: 'Revealer, open your eyes. Point at a player to reveal. [If werewolf: flip card — eliminated. If Lycan: the Lycan is eliminated, not the Revealer. Do NOT indicate to the Revealer whether target is wolf/lycan.] Revealer, close your eyes.',
    moderator_script_tl: 'Revealer, imulat mo ang iyong mga mata. Ituro ang isang player para i-reveal. [Kung werewolf: i-flip ang card — eliminated. Kung Lycan: ang Lycan ang ma-e-eliminate, hindi ang Revealer. HUWAG ipaalam sa Revealer kung wolf/lycan ang target.] Revealer, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Sentinel',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 5,
    is_night_role: 1,
    default_count: 1,
    ability: 'On the first night only, places a shield on one player. That player cannot be targeted by any ability that night.',
    moderator_script: 'Sentinel, open your eyes. Place a shield token on one player. That player is protected from all abilities tonight. Sentinel, close your eyes.',
    moderator_script_tl: 'Sentinel, imulat mo ang iyong mga mata. Lagyan ng shield ang isang player. Protected siya sa lahat ng abilities ngayong gabi. Sentinel, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Beholder',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 47,
    is_night_role: 1,
    default_count: 1,
    ability: 'On the first night, the Beholder learns who the Seer is. The Beholder has no other special ability.',
    moderator_script: 'Beholder, open your eyes. [Point to the Seer.] This player is the Seer. Beholder, close your eyes.',
    moderator_script_tl: 'Beholder, imulat mo ang iyong mga mata. [Ituro ang Seer.] Ito ang Seer. Beholder, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Apprentice Seer',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 48,
    is_night_role: 1,
    default_count: 1,
    ability: 'Becomes the Seer if the original Seer dies. Until then, has no special power at night.',
    moderator_script: 'Apprentice Seer, open your eyes. [If Seer is dead: Point at a player to investigate. Give thumbs up/down. If Seer is alive: Give "wait" signal.] Apprentice Seer, close your eyes.',
    moderator_script_tl: 'Apprentice Seer, imulat mo ang iyong mga mata. [Kung patay na ang Seer: Ituro ang player para i-investigate. Thumbs up/down. Kung buhay pa ang Seer: Wait signal.] Apprentice Seer, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'P.I.',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 55,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, investigates one player. The moderator indicates if that player OR either of their neighbors is a werewolf. The moderator does not say which or how many of those players is a wolf.',
    moderator_script: 'P.I., open your eyes. Point at a player to investigate. [Give thumbs up if that player or either neighbor is a werewolf, thumbs down if none are. Do NOT say which or how many are wolves.] P.I., close your eyes.',
    moderator_script_tl: 'P.I., imulat mo ang iyong mga mata. Ituro ang isang player para i-investigate. [Thumbs up kung ang player o kahit sinong katabi ay werewolf, thumbs down kung wala. HUWAG sabihin kung sino o ilan ang wolf.] P.I., ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Thing (That Goes Bump in the Night)',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 35,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, taps one of their immediate neighbors on the shoulder. That player knows the Thing is sitting next to them.',
    moderator_script: 'Thing, open your eyes. Tap one of your immediate neighbors on the shoulder. [Wait for tap.] Thing, close your eyes.',
    moderator_script_tl: 'Thing, imulat mo ang iyong mga mata. I-tap ang isa sa mga katabi mo sa balikat. [Hintayin ang tap.] Thing, ipikit mo ang iyong mga mata.',
  },

  {
    name: 'Priest',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 6,
    is_night_role: 1,
    default_count: 1,
    ability: 'Once per game (first night), may bless a player who then cannot be eliminated by wolves at night. The Priest may not choose themselves. If the Priest is eliminated after giving their blessing, that player is still protected.',
    moderator_script: 'Priest, open your eyes. Point at a player to bless and protect from werewolves. [You may not choose yourself. This is a one-time ability.] Priest, close your eyes.',
    moderator_script_tl: 'Priest, imulat mo ang iyong mga mata. Ituro ang player na gusto mong basbasan at protektahan mula sa mga werewolf. [Hindi mo pwedeng piliin ang sarili mo. Isang beses lang ito.] Priest, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Aura Seer',
    team: 'village',
    set: 'deluxe',
    night_wake_order: 49,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, learns if a player has any special role (thumbs up) or is a plain Villager (thumbs down). Does not learn the specific role or team.',
    moderator_script: 'Aura Seer, open your eyes. Point at a player. [Give thumbs up if they have ANY special role — village or wolf. Give thumbs down if they are a plain Villager.] Aura Seer, close your eyes.',
    moderator_script_tl: 'Aura Seer, imulat mo ang iyong mga mata. Ituro ang isang player. [Thumbs up kung may special role sila — village man o wolf. Thumbs down kung plain Villager.] Aura Seer, ipikit mo ang iyong mga mata.',
  },

  // ═══ EXTREME SET ══════════════════════════════════════════

  {
    name: 'Bloody Mary',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If a werewolf is lynched during the day, Bloody Mary\'s power activates and a second werewolf is randomly eliminated.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Count Dracula',
    team: 'vampire',
    set: 'extreme',
    night_wake_order: 25,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, bites one player to convert them to a vampire. Cannot bite werewolves. Vampires win if all remaining players are vampires.',
    moderator_script: 'Count Dracula, open your eyes. Point at a player to bite and convert to vampire. [Cannot target werewolves.] Count Dracula, close your eyes.',
    moderator_script_tl: 'Count Dracula, imulat mo ang iyong mga mata. Ituro ang player na gusto mong kagatin at i-convert sa vampire. [Hindi pwede ang mga werewolf.] Count Dracula, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Chupacabra',
    team: 'neutral',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Each night, if alive, automatically kills one werewolf. If no werewolves remain, kills one villager. This is passive — the moderator handles it during resolution.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Vampire',
    team: 'vampire',
    set: 'extreme',
    night_wake_order: 25,
    is_night_role: 1,
    default_count: 1,
    ability: 'Wakes with Count Dracula. Vampires bite one player each night to convert them. Werewolves cannot be converted.',
    moderator_script: 'Vampires, open your eyes. Choose a player to bite and convert. [Cannot target werewolves.] Vampires, close your eyes.',
    moderator_script_tl: 'Mga Vampire, imulat ang inyong mga mata. Pumili ng player na kagatin at i-convert. [Hindi pwede ang mga werewolf.] Mga Vampire, ipikit ang inyong mga mata.',
  },
  {
    name: 'Dire Wolf',
    team: 'werewolf',
    set: 'extreme',
    night_wake_order: 64,
    is_night_role: 1,
    default_count: 1,
    ability: 'On the first night, chooses a bonded player. If the Dire Wolf is eliminated, the bonded player also dies. Participates in the werewolf pack kill.',
    moderator_script: 'Dire Wolf, open your eyes. [Night 1: Choose a player to bond with. If you die, they die too.] Dire Wolf, close your eyes.',
    moderator_script_tl: 'Dire Wolf, imulat mo ang iyong mga mata. [Gabi 1: Pumili ng player na i-bond. Kung mamatay ka, mamamatay din siya.] Dire Wolf, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Fruit Brute',
    team: 'werewolf',
    set: 'extreme',
    night_wake_order: 65,
    is_night_role: 1,
    default_count: 1,
    ability: 'A werewolf with no special power. Wakes with the other werewolves and participates in the pack kill.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Leprechaun',
    team: 'village',
    set: 'extreme',
    night_wake_order: 30,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, chooses two players to swap. Any night actions targeting one of them will instead affect the other.',
    moderator_script: 'Leprechaun, open your eyes. Point at two players to swap for the night. [Note the swap — redirected night actions will affect the swapped player.] Leprechaun, close your eyes.',
    moderator_script_tl: 'Leprechaun, imulat mo ang iyong mga mata. Ituro ang dalawang player na gusto mong i-swap ngayong gabi. [Tandaan ang swap — mga night actions na targeted sa isa ay mapupunta sa kabila.] Leprechaun, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Mummy',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If eliminated by werewolves, the first werewolf who nominated the Mummy as the target dies the following night.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Sorceress',
    team: 'werewolf',
    set: 'extreme',
    night_wake_order: 52,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, searches for the Seer. The moderator indicates if the chosen player is the Seer. Wins with the werewolves but is not a werewolf.',
    moderator_script: 'Sorceress, open your eyes. Point at a player. [Give thumbs up if they are the Seer, thumbs down if not.] Sorceress, close your eyes.',
    moderator_script_tl: 'Sorceress, imulat mo ang iyong mga mata. Ituro ang isang player. [Thumbs up kung siya ang Seer, thumbs down kung hindi.] Sorceress, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Pacifist',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Each day, may reveal their role to prevent a lynch. Can only be used once. After revealing, the day ends with no lynch.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Old Hag',
    team: 'village',
    set: 'extreme',
    night_wake_order: 38,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, chooses one player to banish from the next day\'s discussion. That player cannot speak or vote.',
    moderator_script: 'Old Hag, open your eyes. Point at a player to banish from tomorrow\'s discussion. [That player cannot speak or vote during the day.] Old Hag, close your eyes.',
    moderator_script_tl: 'Old Hag, imulat mo ang iyong mga mata. Ituro ang player na gusto mong i-banish sa discussion bukas. [Hindi siya pwedeng magsalita o bumoto bukas.] Old Hag, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Spellcaster',
    team: 'village',
    set: 'extreme',
    night_wake_order: 40,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, silences one player. That player cannot speak during the next day\'s discussion but can still vote.',
    moderator_script: 'Spellcaster, open your eyes. Point at a player to silence for tomorrow. [That player cannot speak during the day but can vote.] Spellcaster, close your eyes.',
    moderator_script_tl: 'Spellcaster, imulat mo ang iyong mga mata. Ituro ang player na gusto mong patahimikin bukas. [Hindi siya pwedeng magsalita pero pwede bumoto.] Spellcaster, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Tough Guy',
    team: 'village',
    set: 'extreme',
    night_wake_order: 90,
    is_night_role: 1,
    default_count: 1,
    ability: 'If targeted by werewolves, doesn\'t die immediately. Instead, survives until the end of the following day before dying. The Tough Guy is NOT notified that they were targeted.',
    moderator_script: 'Tough Guy does NOT wake up. [The moderator handles this passively during resolution. Do NOT notify the Tough Guy that they were targeted.]',
    moderator_script_tl: 'Tough Guy ay HINDI ginigising. [I-handle ito ng moderator sa resolution. HUWAG ipaalam sa Tough Guy na siya ang target.]',
  },
  {
    name: 'Wolverine',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If eliminated by werewolves at night, the moderator announces that claw marks were found — revealing the kill was done by werewolves.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Hoodlum',
    team: 'neutral',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'On the first night, secretly chooses two players. The Hoodlum wins if both chosen players are eliminated and the Hoodlum survives.',
    moderator_script: 'Hoodlum, open your eyes. Point at two players. You win if both are eliminated and you survive. Hoodlum, close your eyes.',
    moderator_script_tl: 'Hoodlum, imulat mo ang iyong mga mata. Ituro ang dalawang player. Mananalo ka kung pareho silang ma-eliminate at buhay ka pa. Hoodlum, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Cult Leader',
    team: 'cult',
    set: 'extreme',
    night_wake_order: 20,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, recruits one player to the cult. The Cult Leader wins if all surviving players are cult members.',
    moderator_script: 'Cult Leader, open your eyes. Point at a player to recruit to the cult. [Note the recruit.] Cult Leader, close your eyes.',
    moderator_script_tl: 'Cult Leader, imulat mo ang iyong mga mata. Ituro ang player na gusto mong i-recruit sa cult. [Tandaan ang recruit.] Cult Leader, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Doppelganger',
    team: 'village',
    set: 'extreme',
    night_wake_order: 10,
    is_night_role: 1,
    default_count: 1,
    ability: 'On the first night, chooses another player to copy. If that player dies, the Doppelganger takes on their role.',
    moderator_script: 'Doppelganger, open your eyes. Point at a player whose role you wish to copy. [Note the target. If that player dies, Doppelganger assumes their role.] Doppelganger, close your eyes.',
    moderator_script_tl: 'Doppelganger, imulat mo ang iyong mga mata. Ituro ang player na gusto mong i-copy ang role. [Tandaan ang target. Kung mamatay ang player na yun, magiging role mo ang kanya.] Doppelganger, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Ghost',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'When the Ghost is eliminated, each night they may give a one-letter clue to the village by writing it where all can see.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Lycan',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Is on the village team but appears as a werewolf to the Seer.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Mad Bomber',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'When the Mad Bomber is eliminated (day or night), both of their alive neighbors are also eliminated.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Martyr',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Once per game, during the night, may choose to die in place of the werewolves\' target. The moderator wakes them after the wolf kill to offer the choice.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Old Man',
    team: 'village',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'If the Old Man is eliminated by the village (lynched), the village loses all special powers — all remaining villagers become plain Villagers.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Nostradamus',
    team: 'village',
    set: 'extreme',
    night_wake_order: 85,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, points at a player. The moderator indicates if that player will die tonight.',
    moderator_script: 'Nostradamus, open your eyes. Point at a player. [Give thumbs up if that player will die tonight, thumbs down if they will survive.] Nostradamus, close your eyes.',
    moderator_script_tl: 'Nostradamus, imulat mo ang iyong mga mata. Ituro ang isang player. [Thumbs up kung mamamatay siya ngayong gabi, thumbs down kung hindi.] Nostradamus, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Wolf Cub',
    team: 'werewolf',
    set: 'extreme',
    night_wake_order: 70,
    is_night_role: 1,
    default_count: 1,
    ability: 'Wakes with the werewolves. If the Wolf Cub is eliminated, the wolves choose 2 targets the following night instead of 1.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Wolf Man',
    team: 'werewolf',
    set: 'extreme',
    night_wake_order: 0,
    is_night_role: 0,
    default_count: 1,
    ability: 'Is a werewolf, but all roles that detect wolves (Seer, Aura Seer, etc.) see the Wolf Man as a villager. Does not wake at night.',
    moderator_script: '',
    moderator_script_tl: '',
  },
  {
    name: 'Huntress',
    team: 'village',
    set: 'extreme',
    night_wake_order: 76,
    is_night_role: 1,
    default_count: 1,
    ability: 'Once per game, may choose a player to eliminate at night. The Huntress wakes every night even after using their power, to hide when it was used.',
    moderator_script: 'Huntress, open your eyes. Would you like to choose a player to eliminate tonight? [If yes, point to target. One-time use. If already used or declining, shake head.] Huntress, close your eyes.',
    moderator_script_tl: 'Huntress, imulat mo ang iyong mga mata. Gusto mo bang pumili ng player na i-eliminate ngayong gabi? [Kung oo, ituro ang target. Isang beses lang. Kung ginamit na o hindi, iling.] Huntress, ipikit mo ang iyong mga mata.',
  },
  {
    name: 'Troublemaker',
    team: 'village',
    set: 'extreme',
    night_wake_order: 79,
    is_night_role: 1,
    default_count: 1,
    ability: 'Each night, wakes up. If the Troublemaker nods their head, the next day 2 players are eliminated by the village instead of 1.',
    moderator_script: 'Troublemaker, open your eyes. Do you want to cause trouble? [If they nod: tomorrow the village must eliminate 2 players. If they shake head: nothing happens.] Troublemaker, close your eyes.',
    moderator_script_tl: 'Troublemaker, imulat mo ang iyong mga mata. Gusto mo bang gumawa ng gulo? [Kung tumango: bukas kailangang mag-eliminate ang village ng 2 players. Kung umiling: wala mangyayari.] Troublemaker, ipikit mo ang iyong mga mata.',
  },
];
